---
tag_list:
  - list
  - discussion
  - guide
  - gallery
  - meta
  - debug
text_color: rgb(235, 228, 221)
background_color: rgb(54, 59, 62)
favicon: pigeon.ico
font: "basic"
font_size: 7px
title: "laurapigeons epic website :)"
zone_name: "the pigeoncote"
index_name: "home"
user_name: "laurapigeon"
real_name: "Laura Whannabelle"
status_updated: "24 YEARS AGO"
status_emote: grin.png
status_text: "@pigeon why did you let out a high pitched yippee what is going on right now"
info_url: "/contact"
home_url: "https://github.com/laurapigeon/laurapigeon.github.io"
---